Repository Pmanchu-Service/Pmanchu_iOS_V2, pull requests merged in 2025-01, with the labels that each got.

#8 Feature/#7 login
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/Core/Sources/Base/BaseLabel.swift
  Projects/Domain/Sources/Entity/asdf.swift
  Projects/Domain/Sources/Repository/Et.swift
  Projects/Domain/Sources/UseCase/Et.swift
  Projects/Modules/DesignSystem/Sources/Component/Label/PMLabel.swift
  Projects/Modules/ThirdPartyLib/Project.swift
  Projects/Presentation/Sources/Base/BaseViewController.swift
  Projects/Presentation/Sources/Base/BaseViewModel.swift
  Projects/Presentation/Sources/DI/s.swift
  Projects/Presentation/Sources/Et.swift
  Projects/Presentation/Sources/Scene/Login/LoginViewController.swift
  Projects/Presentation/Sources/Scene/Login/LoginViewModel.swift
  Projects/Presentation/Sources/Scene/SignUp/Major/MajorViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Major/MajorViewModel.swift
  Projects/Presentation/Sources/Scene/SignUp/Name/NameViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Name/NameViewModel.swift
  Projects/Presentation/Sources/Scene/SignUp/Rank/RankViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Rank/RankViewModel.swift
  Projects/Presentation/Sources/Scene/SignUp/Self/SelfViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Self/SelfViewModel.swift
  Projects/Presentation/Sources/Scene/SignUp/Skill/SkillViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Skill/SkillViewModel.swift
  Tuist/Dependencies.swift
Labels: FEAT

#10 Feature/#9 module error
  Projects/App/Sources/AppDelegate.swift
  Projects/App/Sources/Et.swift
  Projects/App/Sources/SceneDelegate.swift
  Projects/App/Support/Info.plist
  Projects/Domain/Sources/Repository/Et1.swift
  Projects/Presentation/Sources/Base/BaseViewController.swift
  Projects/Presentation/Sources/Scene/Login/LoginViewModel.swift
  Projects/Presentation/Sources/Scene/SignUp/Major/MajorViewModel.swift
  Projects/Presentation/Sources/Scene/SignUp/Name/NameViewModel.swift
  Scripts/.swiftlint.yml
  Tuist/Config.swift
Labels: FIX, FEAT

#12 Feature/#11 component
  Projects/App/Sources/SceneDelegate.swift
  Projects/Core/Sources/Base/BaseTextField.swift
  Projects/Modules/AppNetwork/Sources/Et.swift
  Projects/Modules/AppNetwork/Sources/Logging/MoyaLoggingPlugin.swift
  Projects/Modules/DesignSystem/Sources/Component/TextField/PMTextField.swift
  Projects/Presentation/Sources/Scene/SignUp/Name/NameViewController.swift
Labels: FEAT

#15 Feature/#14 pm button'
  Projects/Core/Sources/Base/BaseButton.swift
  Projects/Modules/DesignSystem/Sources/Component/Button/PMButton.swift
  Projects/Presentation/Sources/Scene/SignUp/Name/NameViewController.swift
Labels: FEAT

#16 Feature/#13 label component
  Projects/Core/Sources/Base/BaseView.swift
  Projects/Modules/DesignSystem/Sources/Component/View/PMAuthLabelView.swift
  Projects/Modules/DesignSystem/Sources/Typography/PMFont.swift
  Projects/Modules/DesignSystem/Sources/Typography/PMFontStyle.swift
Labels: FEAT

#18 Feature/#17 sign up
  Projects/App/Sources/SceneDelegate.swift
  Projects/Core/Sources/Steps/PMStep.swift
  Projects/Flow/Sources/Et.swift
  Projects/Flow/Sources/SignUp/SignUpFlow.swift
  Projects/Modules/DesignSystem/Sources/Component/TextField/PMTextField.swift
  Projects/Presentation/Sources/Base/BaseViewController.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/DI/s.swift
  Projects/Presentation/Sources/Scene/SignUp/Name/NameViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Name/NameViewModel.swift
  Projects/Presentation/Sources/Scene/SignUp/Rank/RankViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Rank/RankViewModel.swift
Labels: FEAT

#20 chore :: 수정
  Projects/Flow/Sources/App/AppFlow.swift
  Projects/Flow/Sources/App/AppStepper.swift
  Projects/Presentation/Sources/Scene/SignUp/Name/NameViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Name/NameViewModel.swift
  Projects/Presentation/Sources/Scene/SignUp/Rank/RankViewController.swift
Labels: REFACT

#22 Featrue/#21 login appflow icon
  Projects/App/Sources/AppDelegate.swift
  Projects/App/Sources/SceneDelegate.swift
  Projects/Core/Sources/Steps/PMStep.swift
  Projects/Flow/Sources/App/AppFlow.swift
  Projects/Flow/Sources/App/AppStepper.swift
  Projects/Flow/Sources/Login/LoginFlow.swift
  Projects/Flow/Sources/SignUp/SignUpFlow.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/Scene/Login/LoginViewController.swift
  Projects/Presentation/Sources/Scene/Login/LoginViewModel.swift
Labels: FEAT

#26 feat :: XCConfig 세팅 후 repo 옮김
  XCConfig/Pmanchu_iOS_V2/Pmanchu.xcconfig
Labels: FEAT

#28 Feature/#27 di error
  Projects/App/Sources/AppDelegate.swift
  Projects/Core/Sources/Storage/KeyChain/Jwt.swift
  Projects/Data/Sources/DI/DataSourceAssembly.swift
  Projects/Data/Sources/DI/RepositoryAssembly.swift
  Projects/Data/Sources/DI/UseCaseAssembly.swift
  Projects/Data/Sources/DataSource/AuthDataSource.swift
  Projects/Data/Sources/Repository/AuthRepositoryImpl.swift
  Projects/Domain/Sources/Parameter/SignUpRequestParams.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/Scene/SignUp/Name/NameViewModel.swift
Labels: FIX, CHORE

#30 Feature/#29 base url
  Projects/App/Support/Info.plist
  Projects/Core/Sources/Steps/PMStep.swift
  Projects/Flow/Sources/App/AppFlow.swift
  Projects/Flow/Sources/App/AppStepper.swift
  Projects/Flow/Sources/Login/LoginFlow.swift
  Projects/Flow/Sources/SignUp/SignUpFlow.swift
  Projects/Presentation/Sources/Scene/Login/LoginViewModel.swift
  Projects/Presentation/Sources/Scene/SignUp/Email/EmailViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Email/EmailViewModel.swift
  Projects/Presentation/Sources/Scene/SignUp/Name/NameViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Name/NameViewModel.swift
  Projects/Presentation/Sources/Scene/SignUp/Rank/RankViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Rank/RankViewModel.swift
Labels: FEAT, CHORE, SETTING

#32 Feature/#31 email vc
  Projects/Core/Sources/Steps/PMStep.swift
  Projects/Flow/Sources/Auth/AuthFlow.swift
  Projects/Flow/Sources/SignUp/SignUpFlow.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/Scene/SignUp/Email/EmailViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Email/EmailViewModel.swift
  Projects/Presentation/Sources/Scene/SignUp/Name/NameViewModel.swift
  Projects/Presentation/Sources/Scene/SignUp/Rank/RankViewModel.swift
  Projects/Presentation/Sources/Scene/SignUp/Self/SelfViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Self/SelfViewModel.swift
  Projects/Presentation/Sources/Scene/SignUp/Skill/SkillViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Skill/SkillViewModel.swift
Labels: FEAT

#34 Feature/#33 skill
  Projects/Core/Sources/Steps/PMStep.swift
  Projects/Flow/Sources/Auth/AuthFlow.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/Scene/Home/HomeViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Major/MajorViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Major/MajorViewModel.swift
  Projects/Presentation/Sources/Scene/SignUp/Self/SelfViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Self/SelfViewModel.swift
  Projects/Presentation/Sources/Scene/SignUp/Skill/SkillViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Skill/SkillViewModel.swift
Labels: FEAT

#38 Feature/#37 layout tabbar
  Projects/Flow/Sources/App/AppFlow.swift
  Projects/Flow/Sources/Tab/TabFlow.swift
  Projects/Modules/DesignSystem/Sources/Component/Button/SkillAddButton.swift
  Projects/Presentation/Sources/Scene/SignUp/Email/EmailViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Major/MajorViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Major/MajorViewModel.swift
  Projects/Presentation/Sources/Scene/SignUp/Name/NameViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Rank/RankViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Self/SelfViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Skill/Button/SkillAddButton.swift
  Projects/Presentation/Sources/Scene/SignUp/Skill/SkillViewController.swift
Labels: CHORE

#41 Feature/#40 signup name self
  Projects/Domain/Sources/Parameter/SignUpRequestParams.swift
  Projects/Modules/DesignSystem/Resources/Images.xcassets/profile.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images.xcassets/profile.imageset/Profile.svg
  Projects/Modules/DesignSystem/Sources/Image/UIImage+.swift
  Projects/Presentation/Sources/Base/BaseViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Email/EmailViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Name/ImagePicker/NameImagePicker.swift
  Projects/Presentation/Sources/Scene/SignUp/Name/NameViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Name/NameViewModel.swift
  Projects/Presentation/Sources/Scene/SignUp/Self/SelfViewController.swift
  Projects/Presentation/Sources/Scene/SignUp/Self/SelfViewModel.swift
Labels: FEAT, CHORE

#43 Feature/#42 TabBar
  Projects/Flow/Sources/App/AppFlow.swift
  Projects/Flow/Sources/Auth/AuthFlow.swift
  Projects/Flow/Sources/Home/HomeFlow.swift
  Projects/Flow/Sources/Tab/TabFlow.swift
  Projects/Modules/DesignSystem/Sources/Component/CheckBox/ PMMajorSelectView.swift
  Projects/Modules/DesignSystem/Sources/Component/CheckBox/Enum/MajorOption.swift
  Projects/Modules/DesignSystem/Sources/Component/CheckBox/PMCheckBox.swift
  Projects/Presentation/Sources/Base/BaseTabBarController.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
Labels: FEAT, CHORE

#45 Feature/#44 navigation
  Projects/Core/Sources/Steps/PMStep.swift
  Projects/Flow/Sources/Notice/NoticeFlow.swift
  Projects/Modules/DesignSystem/Sources/Component/NavigationBar/PMMainNavigationBar.swift
  Projects/Presentation/Sources/Base/BaseViewController.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/Scene/Home/HomeViewController.swift
  Projects/Presentation/Sources/Scene/Home/HomeViewModel.swift
  Projects/Presentation/Sources/Scene/Notice/NoticeViewController.swift
  Projects/Presentation/Sources/Scene/Notice/NoticeViewModel.swift
  Projects/Presentation/Sources/Scene/UserSearch/UserSearchViewController.swift
Labels: CHORE
